# Generated by Django 6.1 on 2026-08-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="text",
            field=models.TextField(default="lorem ipsum", max_length=1000),
        ),
    ]
