# Generated by Django 5.1.14 on 2026-02-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_alter_comment_text_alter_orderitem_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(allow_unicode=True),
        ),
    ]
